//
//  Source: https://emojiterra.com
//

const fruits = [
    [0, "ðŸ‡", "Grapes"],
    [1, "ðŸˆ", "Melon"],
    [2, "ðŸ‰", "Watermelon"],
    [3, "ðŸŠ", "Tangerine"],
    [4, "ðŸ‹", "Lemon"],
    [5, "ðŸŒ", "Banana"],
    [6, "ðŸ", "Pineapple"],
    [7, "ðŸ¥­", "Mango"],
    [8, "ðŸŽ", "Red Apple"],
    [9, "ðŸ", "Green Apple"],
    [10, "ðŸ", "Pear"],
    [11, "ðŸ‘", "Peach"],
    [12, "ðŸ’", "Cherries"],
    [13, "ðŸ“", "Strawberry"],
    [14, "ðŸ«", "Blueberries"],
    [15, "ðŸ¥", "Kiwi Fruit"],
    [16, "ðŸ…", "Tomato"],
    [17, "ðŸ«’", "Olive"],
    [18, "ðŸ¥¥", "Coconut"],
  ];
  
  const food = [
    [0, "ðŸž", "Bread"],
    [1, "ðŸ¥", "Croissant"],
    [2, "ðŸ¥–", "Baguette Bread"],
    [3, "ðŸ«“", "Flatbread"],
    [4, "ðŸ¥¨", "Pretzel"],
    [5, "ðŸ¥¯", "Bagel"],
    [6, "ðŸ¥ž", "Pancakes"],
    [7, "ðŸ§‡", "Waffle"],
    [8, "ðŸ§€", "Cheese Wedge"],
    [9, "ðŸ–", "Meat On Bone"],
    [10, "ðŸ—", "Poultry Leg"],
    [11, "ðŸ¥©", "Cut Of Meat"],
    [12, "ðŸ¥“", "Bacon"],
    [13, "ðŸ”", "Hamburger"],
    [14, "ðŸŸ", "French Fries"],
    [15, "ðŸ•", "Pizza"],
    [16, "ðŸŒ­", "Hot Dog"],
    [17, "ðŸ¥ª", "Sandwich"],
    [18, "ðŸŒ®", "Taco"],
    [19, "ðŸŒ¯", "Burrito"],
    [20, "ðŸ«”", "Tamale"],
    [21, "ðŸ¥™", "Stuffed Flatbread"],
    [22, "ðŸ§†", "Falafel"],
    [23, "ðŸ¥š", "Egg"],
    [24, "ðŸ³", "Cooking"],
    [25, "ðŸ¥˜", "Shallow Pan Of Food"],
    [26, "ðŸ²", "Pot Of Food"],
    [27, "ðŸ«•", "Fondue"],
    [28, "ðŸ¥£", "Bowl With Spoon"],
    [29, "ðŸ¥—", "Green Salad"],
    [30, "ðŸ¿", "Popcorn"],
    [31, "ðŸ§ˆ", "Butter"],
    [32, "ðŸ§‚", "Salt"],
    [33, "ðŸ¥«", "Canned Food"],
  ];
  
  const drinks = [
    [0, "ðŸ¼", "Baby Bottle"],
    [1, "ðŸ¥›", "Glass Of Milk"],
    [2, "â˜•", "Hot Beverage"],
    [3, "ðŸ«–", "Teapot"],
    [4, "ðŸµ", "Teacup Without Handle"],
    [5, "ðŸ¶", "Sake"],
    [6, "ðŸ¾", "Bottle With Popping Cork"],
    [7, "ðŸ·", "Wine Glass"],
    [8, "ðŸ¸", "Cocktail Glass"],
    [9, "ðŸ¹", "Tropical Drink"],
    [10, "ðŸº", "Beer Mug"],
    [11, "ðŸ»", "Clinking Beer Mugs"],
    [12, "ðŸ¥‚", "Clinking Glasses"],
    [13, "ðŸ¥ƒ", "Tumbler Glass"],
    [14, "ðŸ«—", "Pouring Liquid"],
    [15, "ðŸ¥¤", "Cup With Straw"],
    [16, "ðŸ§‹", "Bubble Tea"],
    [17, "ðŸ§ƒ", "Beverage Box"],
    [18, "ðŸ§‰", "Mate"],
    [19, "ðŸ§Š", "Ice"],
  ];
  
  const transport = [
    [0, "ðŸš‚", "Locomotive"],
    [1, "ðŸšƒ", "Railway Car"],
    [2, "ðŸš„", "High-speed Train"],
    [3, "ðŸš…", "Bullet Train"],
    [4, "ðŸš†", "Train"],
    [5, "ðŸš‡", "Metro"],
    [6, "ðŸšˆ", "Light Rail"],
    [7, "ðŸš‰", "Station"],
    [8, "ðŸšŠ", "Tram"],
    [9, "ðŸš", "Monorail"],
    [10, "ðŸšž", "Mountain Railway"],
    [11, "ðŸš‹", "Tram Car"],
    [12, "ðŸšŒ", "Bus"],
    [13, "ðŸš", "Oncoming Bus"],
    [14, "ðŸšŽ", "Trolleybus"],
    [15, "ðŸš", "Minibus"],
    [16, "ðŸš‘", "Ambulance"],
    [17, "ðŸš’", "Fire Engine"],
    [18, "ðŸš“", "Police Car"],
    [19, "ðŸš”", "Oncoming Police Car"],
    [20, "ðŸš•", "Taxi"],
    [21, "ðŸš–", "Oncoming Taxi"],
    [22, "ðŸš—", "Automobile"],
    [23, "ðŸš˜", "Oncoming Automobile"],
    [24, "ðŸš™", "Sport Utility Vehicle"],
    [25, "ðŸ›»", "Pickup Truck"],
    [26, "ðŸšš", "Delivery Truck"],
    [27, "ðŸš›", "Articulated Lorry"],
    [28, "ðŸšœ", "Tractor"],
    [29, "ðŸŽï¸", "Racing Car"],
    [30, "ðŸï¸", "Motorcycle"],
    [31, "ðŸ›µ", "Motor Scooter"],
    [32, "ðŸ¦½", "Manual Wheelchair"],
    [33, "ðŸ¦¼", "Motorized Wheelchair"],
    [34, "ðŸ›º", "Auto Rickshaw"],
    [35, "ðŸš²", "Bicycle"],
    [36, "ðŸ›´", "Kick Scooter"],
    [37, "ðŸ›¹", "Skateboard"],
    [38, "ðŸ›¼", "Roller Skate"],
  ];
  
  const letters = [
    [0, "A", "A"],
    [1, "B", "B"],
    [2, "C", "C"],
    [3, "D", "D"],
    [4, "E", "E"],
    [5, "F", "F"],
    [6, "G", "G"],
    [7, "H", "H"],
    [8, "I", "I"],
    [9, "K", "K"],
    [10, "L", "L"],
    [11, "M", "M"],
    [12, "N", "N"],
    [13, "O", "O"],
    [14, "P", "P"],
  ];
  
  export default { fruits, food, drinks, transport, letters };